
const products = [
  {
    id: 1,
    name: "Spicy Potato Chips",
    category: "Snacks and Sweets",
    weight: "150g",
    price: 99,
    mrp: 149,
    discount: "34% Off",
    image: "src/assets/images/Spicy Potato Chips.jpg",
    badge: "Deal of the Day",
    points: 2,
    isVeg: true,           
  },
  {
    id: 2,
    name: "Organic Green Tea",
    category: "Beverages",
    weight: "100g (20 Tea Bags)",
    price: 199,
    mrp: 299,
    discount: "33% Off",
    image: "src/assets/images/Organic Green Tea.jpg",
    badge: "Biggest Savings",
    points: 1,
    isVeg: true,
  },
  {
    id: 3,
    name: "Whole Wheat Pasta",
    category: "Grains",
    weight: "500g",
    price: 129,
    mrp: 199,
    discount: "35% Off",
    image: "src/assets/images/Whole Wheat Pasta.jpg",
    badge: "Healthy Pick",
    points: 2,
    isVeg: true,
  },
  {
    id: 4,
    name: "Organic Honey",
    category: "Ready to eat",
    weight: "500g",
    price: 350,
    mrp: 499,
    discount: "30% Off",
    image: "src/assets/images/Organic Honey.jpg",
    points: 1,
    isVeg: true,
  },
  {
    id: 5,
    name: "Masala Peanuts",
    category: "Snacks and Sweets",
    weight: "200g",
    price: 149,
    mrp: 199,
    discount: "25% Off",
    image: "src/assets/images/Masala Peanuts.jpg",
    badge: "Most Loved",
    points: 2,
    isVeg: true,
  },
  {
    id: 6,
    name: "Organic Quinoa",
    category: "Grains",
    weight: "500g",
    price: 399,
    mrp: 599,
    discount: "34% Off",
    image: "src/assets/images/Organic Quinoa.jpg",
    points: 1,
    isVeg: true,
  },
  {
    id: 7,
    name: "Organic Coconut Oil",
    category: "Ready to eat",
    weight: "1L",
    price: 249,
    mrp: 399,
    discount: "38% Off",
    image: "src/assets/images/Organic Coconut Oil.jpg",
    badge: "Best Seller",
    points: 2,
    isVeg: true,
  },
  {
    id: 8,
    name: "Ground Turmeric",
    category: "Spices and Masalas",
    weight: "100g",
    price: 49,
    mrp: 79,
    discount: "38% Off",
    image: "src/assets/images/Ground Turmeric.jpg",
    points: 1,
    isVeg: true,
  },
  {
    id: 9,
    name: "Fresh Greek Yogurt",
    category: "Dairy and egg",
    weight: "400g",
    price: 129,
    mrp: 179,
    discount: "28% Off",
    image: "src/assets/images/Fresh Greek Yogurt.jpg",
    badge: "Trending Now",
    points: 2,
    isVeg: true,
  },
  {
    id: 10,
    name: "Dark Chocolate Truffles",
    category: "Snacks and Sweets",
    weight: "150g",
    price: 299,
    mrp: 399,
    discount: "25% Off",
    image: "src/assets/images/Dark Chocolate Truffles.jpg",
    points: 1,
    isVeg: true,
  },
  {
    id: 11,
    name: "Salted Pretzels",
    category: "Snacks and Sweets",
    weight: "250g",
    price: 99,
    mrp: 129,
    discount: "23% Off",
    image: "src/assets/images/Salted Pretzels.jpg",
    points: 1,
    isVeg: true,
  },
  {
    id: 12,
    name: "Brown Basmati Rice",
    category: "Grains",
    weight: "1kg",
    price: 199,
    mrp: 249,
    discount: "20% Off",
    image: "src/assets/images/Brown Basmati Rice.jpg",
    points: 2,
    isVeg: true,
  },
  {
    id: 13,
    name: "Fresh Eggs (Dozen)",
    category: "Dairy and egg",
    weight: "12 pieces",
    price: 99,
    mrp: 120,
    discount: "18% Off",
    image: "src/assets/images/Fresh Eggs (Dozen).jpg",
    badge: "Farm Fresh",
    points: 1,
    isVeg: true,           
  },
  {
    id: 14,
    name: "Garam Masala",
    category: "Spices and Masalas",
    weight: "50g",
    price: 59,
    mrp: 75,
    discount: "21% Off",
    image: "src/assets/images/Garam Masala.jpg",
    points: 1,
    isVeg: true,
  },
  {
    id: 15,
    name: "Instant Coffee",
    category: "Beverages",
    weight: "100g",
    price: 149,
    mrp: 199,
    discount: "25% Off",
    image: "src/assets/images/Instant Coffee.jpg",
    points: 1,
    isVeg: true,
  },
  {
    id: 16,
    name: "Fresh Salmon Fillet",
    category: "Meat and Seafood",
    weight: "300g",
    price: 499,
    mrp: 649,
    discount: "23% Off",
    image: "src/assets/images/Fresh Salmon Fillet.jpg",
    points: 2,
    isVeg: false,          
  },
  {
    id: 17,
    name: "Almond Milk",
    category: "Beverages",
    weight: "1L",
    price: 199,
    mrp: 249,
    discount: "20% Off",
    image: "src/assets/images/Almond Milk.jpg",
    badge: "Vegan Favorite",
    points: 1,
    isVeg: true,
  }
];

export default products;
