
const products = [
  {
    id: 1,
    name: "Spicy Potato Chips",
    category: "Snacks and Sweets",
    weight: "150g",
    price: 99,
    mrp: 149,
    discount: "34% Off",
    image: "src/assets/images/potato_chips.jpg",
    badge: "Deal of the Day",
    points: 2,
    isVeg: true,           
  },
  {
    id: 2,
    name: "Organic Green Tea",
    category: "Beverages",
    weight: "100g (20 Tea Bags)",
    price: 199,
    mrp: 299,
    discount: "33% Off",
    image: "src/assets/images/green_tea.jpg",
    badge: "Biggest Savings",
    points: 1,
    isVeg: true,
  },
  {
    id: 3,
    name: "Whole Wheat Pasta",
    category: "Grains",
    weight: "500g",
    price: 129,
    mrp: 199,
    discount: "35% Off",
    image: "src/assets/images/whole_wheat_pasta.jpg",
    badge: "Healthy Pick",
    points: 2,
    isVeg: true,
  },
  {
    id: 4,
    name: "Organic Honey",
    category: "Ready to eat",
    weight: "500g",
    price: 350,
    mrp: 499,
    discount: "30% Off",
    image: "src/assets/images/honey.jpg",
    points: 1,
    isVeg: true,
  },
  {
    id: 5,
    name: "Masala Peanuts",
    category: "Snacks and Sweets",
    weight: "200g",
    price: 149,
    mrp: 199,
    discount: "25% Off",
    image: "src/assets/images/masala_peanuts.jpg",
    badge: "Most Loved",
    points: 2,
    isVeg: true,
  },
  {
    id: 6,
    name: "Organic Quinoa",
    category: "Grains",
    weight: "500g",
    price: 399,
    mrp: 599,
    discount: "34% Off",
    image: "src/assets/images/quinoa.jpg",
    points: 1,
    isVeg: true,
  },
  {
    id: 7,
    name: "Organic Coconut Oil",
    category: "Ready to eat",
    weight: "1L",
    price: 249,
    mrp: 399,
    discount: "38% Off",
    image: "src/assets/images/coconut_oil.jpg",
    badge: "Best Seller",
    points: 2,
    isVeg: true,
  },
  {
    id: 8,
    name: "Ground Turmeric",
    category: "Spices and Masalas",
    weight: "100g",
    price: 49,
    mrp: 79,
    discount: "38% Off",
    image: "src/assets/images/ground_turmeric.jpg",
    points: 1,
    isVeg: true,
  },
  {
    id: 9,
    name: "Fresh Greek Yogurt",
    category: "Dairy and egg",
    weight: "400g",
    price: 129,
    mrp: 179,
    discount: "28% Off",
    image: "src/assets/images/greek_yogurt.jpg",
    badge: "Trending Now",
    points: 2,
    isVeg: true,
  },
  {
    id: 10,
    name: "Dark Chocolate Truffles",
    category: "Snacks and Sweets",
    weight: "150g",
    price: 299,
    mrp: 399,
    discount: "25% Off",
    image: "src/assets/images/dark_chocolate.jpg",
    points: 1,
    isVeg: true,
  },
  {
    id: 11,
    name: "Salted Pretzels",
    category: "Snacks and Sweets",
    weight: "250g",
    price: 99,
    mrp: 129,
    discount: "23% Off",
    image: "src/assets/images/salted_pretzels.jpg",
    points: 1,
    isVeg: true,
  },
  {
    id: 12,
    name: "Brown Basmati Rice",
    category: "Grains",
    weight: "1kg",
    price: 199,
    mrp: 249,
    discount: "20% Off",
    image: "src/assets/images/basmati_rice.jpg",
    points: 2,
    isVeg: true,
  },
  {
    id: 13,
    name: "Fresh Eggs (Dozen)",
    category: "Dairy and egg",
    weight: "12 pieces",
    price: 99,
    mrp: 120,
    discount: "18% Off",
    image: "src/assets/images/eggs.jpg",
    badge: "Farm Fresh",
    points: 1,
    isVeg: true,           
  },
  {
    id: 14,
    name: "Garam Masala",
    category: "Spices and Masalas",
    weight: "50g",
    price: 59,
    mrp: 75,
    discount: "21% Off",
    image: "src/assets/images/garam_masala.jpg",
    points: 1,
    isVeg: true,
  },
  {
    id: 15,
    name: "Instant Coffee",
    category: "Beverages",
    weight: "100g",
    price: 149,
    mrp: 199,
    discount: "25% Off",
    image: "src/assets/images/instant_coffee.jpg",
    points: 1,
    isVeg: true,
  },
  {
    id: 16,
    name: "Fresh Salmon Fillet",
    category: "Meat and Seafood",
    weight: "300g",
    price: 499,
    mrp: 649,
    discount: "23% Off",
    image: "src/assets/images/fresh_salmon.jpg",
    points: 2,
    isVeg: false,          
  },
  {
    id: 17,
    name: "Almond Milk",
    category: "Beverages",
    weight: "1L",
    price: 199,
    mrp: 249,
    discount: "20% Off",
    image: "src/assets/images/almond_milk.jpg",
    badge: "Vegan Favorite",
    points: 1,
    isVeg: true,
  }
];

export default products;
