const products = [
  {
    id: 1,
    name: "Spicy Potato Chips",
    category: "Snacks & Beverages",
    weight: "150g",
    price: 99,
    mrp: 149,
    discount: "34% Off",
    image: "src/assets/spicy potato chips.png",
    badge: "Deal of the Day",
    points: 2,
  },
  {
    id: 2,
    name: "Organic Green Tea",
    category: "Snacks & Beverages",
    weight: "100g (20 Tea Bags)",
    price: 199,
    mrp: 299,
    discount: "33% Off",
    image: "src/assets/green tea.png",
    badge: "Biggest Savings",
    points: 1,
  },
  {
    id: 3,
    name: "Whole Wheat Pasta",
    category: "Grocery",
    weight: "500g",
    price: 129,
    mrp: 199,
    discount: "35% Off",
    image: "src/assets/wholw wheat.png",
    points: 2,
  },
  {
    id: 4,
    name: "Organic Honey",
    category: "Grocery",
    weight: "500g",
    price: 350,
    mrp: 499,
    discount: "30% Off",
    image: "src/assets/organic honey.png",
    badge: "Daily Discounts",
    points: 1,
  },
  {
    id: 5,
    name: "Masala Peanuts Most Loved",
    category: "Snacks & Beverages",
    weight: "200g",
    price: 149,
    mrp: 199,
    discount: "25% Off",
    image: "src/assets/masala peanuts.png",
    badge: "Most Loved",
    points: 2,
  },
  {
    id: 6,
    name: "Organic Quinoa",
    category: "Grains and Staples",
    weight: "500g",
    price: 399,
    mrp: 599,
    discount: "34% Off",
    image: "src/assets/organic quiona.png",
    points: 1,
  },
  {
    id: 7,
    name: "Organic Coconut Oil",
    category: "Grocery",
    weight: "1L",
    price: 249,
    mrp: 399,
    discount: "38% Off",
    image: "src/assets/organic coconut oil.png",
    points: 2,
  },
  {
    id: 8,
    name: "Ground Turmeric",
    category: "Herbs and Spices",
    weight: "100g",
    price: 49,
    mrp: 79,
    discount: "38% Off",
    image: "src/assets/ground turmeric.png",
    points: 1,
  },
  {
    id: 9,
    name: "Fresh Greek Yogurt",
    category: "Dairy and Eggs",
    weight: "400g",
    price: 129,
    mrp: 179,
    discount: "28% Off",
    image: "src/assets/fresh greek yogurt.png",
    badge: "Trending Now",
    points: 2,
  },
  {
    id: 10,
    name: "Dark Chocolate Truffles",
    category: "Confectionery",
    weight: "150g",
    price: 299,
    mrp: 399,
    discount: "25% Off",
    image: "src/assets/dark chocalate turffiles.png",
    badge: "Best of the Best",
    points: 1,
  },
  {
    id: 11,
    name: "Salted Pretzels",
    category: "Snacks and Beverages",
    weight: "250g",
    price: 99,
    mrp: 129,
    discount: "23% Off",
    image: "src/assets/salted pretzels.png",
    points: 1,
  },
  {
    id: 12,
    name: "Brown Basmati Rice",
    category: "Grains and Staples",
    weight: "1kg",
    price: 199,
    mrp: 249,
    discount: "20% Off",
    image: "src/assets/brown busmathi rice.png",
    points: 2,
  },
  {
    id: 13,
    name: "Holiday Cheer Pack",
    category: "Gifting",
    contents: [
      "1 Box of Organic Herbal Tea",
      "1 Jar of Local Honey",
      "1 Pack of Almonds",
    ],
    price: 1499,
    mrp: 2000,
    discount: "25% Off",
    image: "src/assets/holiday cheer.png",
    points: '',
  },
  {
    id: 14,
    name: "Luxury Gourmet Basket",
    category: "Gifting",
    contents: [
      "1 Bottle of Fine Olive Oil",
      "1 Box of Dark Chocolate Truffles",
      "1 Pack of Premium Coffee Beans",
    ],
    price: 3499,
    mrp: 4500,
    discount: "22% Off",
    image: "src/assets/luxury gurmate.png",
    badge: "Surprise & Delight",
    points: '',
  },
  {
    id: 15,
    name: "Healthy Snack Bundle",
    category: "Gifting",
    contents: [
      "1 Box of Protein Bars",
      "1 Pack of Dried Fruits",
      "1 Pack of Roasted Chickpeas",
    ],
    price: 799,
    mrp: 1099,
    discount: "27% Off",
    image: "src/assets/healthy snack.png",
    points: '',
  },
  {
    id: 16,
    name: "Sweets and Treats",
    category: "Gifting",
    contents: [
      "1 Box of Assorted Cookies",
      "1 Jar of Mixed Fruit Jam",
      "1 Pack of Premium Chocolates",
    ],
    price: 899,
    mrp: 1200,
    discount: "25% Off",
    image: "src/assets/sweets and treats.png",
    points: '',
  },
];

export default products;
